version: '3.4'
services:
  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.rpi
      cache_from:
        - tjanas94/library-backend
    image: tjanas94/library-backend

  builder:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.rpi
      target: build
      args:
        - FRONTEND_ADMIN_EMAIL=${FRONTEND_ADMIN_EMAIL}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      cache_from:
        - tjanas94/library-frontend-builder
    image: tjanas94/library-frontend-builder

  frontend:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.rpi
      args:
        - FRONTEND_ADMIN_EMAIL=${FRONTEND_ADMIN_EMAIL}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
        - FRONTEND_SSL_PORT=${FRONTEND_SSL_PORT}
      cache_from:
        - tjanas94/library-frontend-builder
        - tjanas94/library-frontend
    image: tjanas94/library-frontend
