version: '2.2'
services:
  db:
    image: postgres:10-alpine
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    volumes:
     - db-data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:4.0
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    env_file: .env

  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "${RABBITMQ_EXTERNAL_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    env_file: .env

  worker:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: python:library
    command: run_worker.sh
    volumes:
      - ./backend:/usr/src/app
      - static-files:/usr/src/app/static
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PORT=5672

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: python:library
    command: run_web.sh
    ports:
      - "${BACKEND_WEB_PORT:-8000}:8000"
      - "${BACKEND_DEBUG_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - static-files:/usr/src/app/static
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PORT=5672

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: node:library
    ports:
      - "${FRONTEND_WEB_PORT:-9000}:9000"
    volumes:
      - ./frontend:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    links:
      - backend
    env_file: .env

volumes:
  db-data:
  redis-data:
  rabbit-data:
  static-files:
  node-modules:
