version: '2.2'
services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: python:biblioteka
    ports:
      - "${BACKEND_WEB_PORT:-8000}:8000"
      - "${BACKEND_DEBUG_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - static-volume:/usr/src/app/static
    links:
      - postgres
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: postgres:10-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
     - db-volume:/var/lib/postgresql/data
    env_file: .env

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: node:biblioteka
    ports:
      - "${FRONTEND_WEB_PORT:-9000}:9000"
    volumes:
      - ./frontend:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    links:
      - python
    env_file: .env

volumes:
  db-volume:
  static-volume:
  node-modules:
